# Generated by Django 4.2 on 2023-12-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='lumens/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
