# Generated by Django 4.2 on 2024-01-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_code_alter_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotions/', verbose_name='Фото')),
                ('code', models.CharField(max_length=100, verbose_name='Артикул')),
                ('info', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
