# Generated by Django 4.2 on 2024-01-23 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotions',
            name='code',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='image',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='info',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='price',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='quantity',
        ),
        migrations.AddField(
            model_name='promotions',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Пром-товар'),
        ),
    ]
