# Generated by Django 4.2 on 2024-01-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_promotions_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
